In [1]:
import numpy as np
import pandas as pd
import nltk
import string
from nltk.corpus import stopwords

In [2]:
df = pd.read_csv("emails.csv")

In [3]:
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [4]:
df.shape

(5728, 2)

In [5]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.shape

(5695, 2)

In [8]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

* remove punctuation
* remove stopwords
* return a list of clean words

In [9]:
def process_test(text):
    #1 remove punctuation 
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = "".join(nopunc)
    
    #2 remove stopwords
    
    clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words("english")]
    
    # return clean words
    
    return clean_words
    

In [10]:
# show the tokenization ( a list of tokens also called lemmmas )
df["text"].head().apply(process_test)

0    [u, b, j, e, c, n, u, r, l, l, r, r, e, b, l, ...
1    [u, b, j, e, c, h, e, c, k, r, n, g, g, u, n, ...
2    [u, b, j, e, c, u, n, b, e, l, e, v, b, l, e, ...
3    [u, b, j, e, c, 4, c, l, r, p, r, n, n, g, p, ...
4    [u, b, j, e, c, n, h, v, e, n, e, g, e, f, w, ...
Name: text, dtype: object

In [11]:
# convert a token for texts into matrix
from sklearn.feature_extraction.text import CountVectorizer
message_bow = CountVectorizer(analyzer=process_test).fit_transform(df["text"])

In [35]:
# now we gonna split the data into train & test
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(message_bow, df["spam"], test_size = 0.20, random_state=0)




In [36]:
# import Naive baise model
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(x_train, y_train)

In [37]:
# print the prediction
print(classifier.predict(x_train))

# actual values
print(y_train.values)



[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [38]:
# Evaluate the training model

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
y_pred = classifier.predict(x_train)
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.74      0.81      3457
           1       0.47      0.73      0.57      1099

    accuracy                           0.74      4556
   macro avg       0.68      0.73      0.69      4556
weighted avg       0.79      0.74      0.75      4556



In [39]:
print(confusion_matrix(y_train,y_pred))

[[2546  911]
 [ 294  805]]


In [40]:
print(accuracy_score(y_train,y_pred))

0.735513608428446


In [41]:
# print the prediction
print(classifier.predict(x_test))

# actual values
print(y_test.values)


[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [42]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
y_pred = classifier.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.76      0.82       870
           1       0.48      0.72      0.57       269

    accuracy                           0.75      1139
   macro avg       0.69      0.74      0.70      1139
weighted avg       0.80      0.75      0.76      1139



In [43]:
print(confusion_matrix(y_test,y_pred))

[[660 210]
 [ 76 193]]


In [44]:
print(accuracy_score(y_test,y_pred))

0.7489025460930641
